// Generated by death_atlas.py; order matches vf_status_catalog.h.
#ifndef VF_DEATH_ATLAS_H
#define VF_DEATH_ATLAS_H
#include "vf_death_motion.h"
namespace vfdeath {
struct Profile {const char* effect;const char* label;int motions[2],count;float fxSeconds;};
static const Profile Profiles[]={
{"hydro","Perte d equilibre",{6,4},2,3.7f},
{"electro","Contractions",{12,0},1,2.1f},
{"cryo","Effondrement raide",{3,0},1,1.6f},
{"thermal","Douleur et recul",{10,0},1,4.1f},
{"toxic","Agonie lente",{8,0},1,6.2f},
{"corrosion","Douleur et chute",{11,5},2,4.0f},
{"sonic","Chute laterale",{9,0},1,2.8f},
{"kinetic","Recul violent",{7,0},1,3.9f},
{"arc_chain","Contractions et gouttes",{12,0},1,2.1f},
{"superconduction","Contractions et givre",{12,0},1,2.1f},
{"shatter","Rupture et chute raide",{3,0},1,1.8f},
{"resonant_impact","Impact avec rotation",{14,7},2,3.9f},
{"cavitation","Douleur et chute laterale",{11,0},1,4.0f},
{"caustic_contagion","Agonie corrosive",{8,0},1,6.2f},
{"toxic_ignition","Douleur et combustion",{10,0},1,4.1f},
{"steam_veil","Recul dans la vapeur",{10,0},1,4.1f},
};
static const int ProfileCount=sizeof(Profiles)/sizeof(Profiles[0]);
inline const Profile* ProfileFor(int effect){return effect>=0&&effect<ProfileCount?&Profiles[effect]:0;}
inline int AutomaticMotion(int effect,int missing,int choice){const Profile* p=ProfileFor(effect);if(p)return p->motions[(unsigned int)choice%p->count];if(missing&1)return 13;return 2+(unsigned int)choice%3;}
}
#endif
