// Generated by model_contract.py from data/model_contract.json; do not edit.
#ifndef VF_MODEL_CONTRACT_H
#define VF_MODEL_CONTRACT_H
#include <string.h>
namespace vf {
struct ModelTraits { const char* key; int feedMount; bool supportGrip; };
static const ModelTraits ModelTraitTable[] = {
 {"r01_receiver_a", 0, false},
 {"r01_receiver_b", 0, false},
 {"r01_receiver_c", 0, false},
 {"r01_receiver_d", 0, false},
 {"r01_receiver_side", 1, false},
 {"r01_receiver_top", 2, false},
 {"r01_receiver_arch", 0, false},
 {"r01_receiver_arch_top", 2, false},
 {"r01_receiver_gyre", 0, false},
 {"r01_underbarrel_a", 0, true},
 {"r01_underbarrel_b", 0, false},
 {"r01_underbarrel_c", 0, false},
 {"r01_underbarrel_d", 0, false},
};
inline const ModelTraits* FindModelTraits(const char* key) {
 if(!key)return NULL;
 for(unsigned int i=0;i<sizeof(ModelTraitTable)/sizeof(*ModelTraitTable);++i)
  if(!strcmp(key,ModelTraitTable[i].key))return &ModelTraitTable[i];
 return NULL;
}
struct ModelCarrier { const char* firstPerson; const char* foregrip; const char* thirdPerson; };
static const ModelCarrier ModelCarriers[] = {
 {"models/vf_r01/r01_rig.mdl", "models/vf_r01/r01_rig_fg.mdl", "models/vf_r01/r01_tp.mdl"},
 {"models/vf_r01/r01_rig_side.mdl", "models/vf_r01/r01_rig_side_fg.mdl", "models/vf_r01/r01_tp_side.mdl"},
 {"models/vf_r01/r01_rig_top.mdl", "models/vf_r01/r01_rig_top_fg.mdl", "models/vf_r01/r01_tp_top.mdl"},
};
inline const ModelCarrier& Carrier(int mount) { return ModelCarriers[mount>=0&&mount<3?mount:0]; }
static const char* const FirstPersonWeaponSocket = "Bone76";
static const char* const FirstPersonFeedSocket = "Bone71";
static const char* const FirstPersonChamberSocket = "R01_Bolt";
static const char* const ThirdPersonWeaponSocket = "VF_Weapon";
static const char* const ThirdPersonFeedSocket = "VF_Magazine";
static const char* const ThirdPersonChamberSocket = "VF_Bolt";
static const int PersonaSequenceCount = 77;
}
#endif
