// Generated by vector-fields/build_materials.py; edit data/combat-materials.json.
#ifndef VF_MATERIAL_CATALOG_H
#define VF_MATERIAL_CATALOG_H
namespace vfc {
struct Material {const char* id;const char* family;float densityKgM3,resistanceJPerMm;bool calibrated;};
struct LayerDefinition {int material;float thicknessMm;};
struct Profile {const char* id;int count;LayerDefinition layers[4];};
enum MaterialId {Mat_unknown=0,Mat_flesh=1,Mat_textile=2,Mat_leather=3,Mat_rubber=4,Mat_steel=5,Mat_glass=6,Mat_concrete=7,Mat_wood=8,Mat_soil=9,Mat_ceramic=10,Mat_water=11,Mat_composite=12,Mat_snow=13,MaterialCount};
enum ProfileId {Profile_unknown=0,Profile_uniform=1,Profile_glove=2,Profile_boot=3,Profile_metal=4,ProfileCount};
static const Material materials[MaterialCount]={
{"unknown","unknown",-1.0f,-1.0f,false},
{"flesh","biological",1000.000000f,-1.0f,false},
{"textile","fabric",500.000000f,-1.0f,false},
{"leather","organic",850.000000f,-1.0f,false},
{"rubber","polymer",1100.000000f,-1.0f,false},
{"steel","metal",7800.000000f,-1.0f,false},
{"glass","mineral",2500.000000f,-1.0f,false},
{"concrete","mineral",2400.000000f,-1.0f,false},
{"wood","organic",600.000000f,-1.0f,false},
{"soil","granular",1700.000000f,-1.0f,false},
{"ceramic","mineral",2300.000000f,-1.0f,false},
{"water","fluid",1000.000000f,-1.0f,false},
{"composite","composite",-1.0f,-1.0f,false},
{"snow","granular",-1.0f,-1.0f,false},
};
static const Profile profiles[ProfileCount]={
{"unknown",1,{{Mat_unknown,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f}}},
{"uniform",1,{{Mat_textile,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f}}},
{"glove",1,{{Mat_leather,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f}}},
{"boot",1,{{Mat_rubber,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f}}},
{"metal",1,{{Mat_steel,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f},{Mat_unknown,-1.0f}}},
};
enum EquipmentSlot {Slot_head=0,Slot_shoulders=1,Slot_gloves=2,Slot_torso=3,Slot_belt=4,Slot_legs=5,Slot_boots=6,Slot_shield=7,Slot_special=8,Slot_receiver=9,Slot_barrel=10,Slot_muzzle=11,Slot_feed=12,Slot_chamber=13,Slot_ammo=14,Slot_projectile=15,Slot_optic=16,Slot_underbarrel=17,Slot_grip=18,Slot_power=19,Slot_cooling=20};
static const int slotProfiles[21]={Profile_unknown,Profile_unknown,Profile_glove,Profile_uniform,Profile_unknown,Profile_uniform,Profile_boot,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown,Profile_unknown};
struct ItemOverride {const char* key;int profile;};
static const ItemOverride itemOverrides[]={
{"",Profile_unknown}};
inline int TextureMaterial(char type){switch(type){
case 'C':return Mat_concrete;
case 'M':return Mat_steel;
case 'D':return Mat_soil;
case 'V':return Mat_steel;
case 'G':return Mat_steel;
case 'T':return Mat_ceramic;
case 'S':return Mat_water;
case 'W':return Mat_wood;
case 'P':return Mat_composite;
case 'Y':return Mat_glass;
case 'F':return Mat_flesh;
case 'N':return Mat_snow;
default:return Mat_unknown;}}
enum ProjectileNature {NatureUnknown,Kinetic,Blunt,Thermal,Explosive,Chemical,Electrical};
inline const char* NatureKey(ProjectileNature n){static const char* keys[]={"unknown","kinetic","blunt","thermal","explosive","chemical","electrical"};return keys[n>=NatureUnknown&&n<=Electrical?n:NatureUnknown];}
struct ProjectileDefinition {const char* id;int nativeType;ProjectileNature nature;float massKg,speedMS;bool calibrated;};
static const ProjectileDefinition projectiles[]={
{"none",0,(ProjectileNature)0,-1.0f,-1.0f,false},
{"player_9mm",1,(ProjectileNature)1,-1.0f,-1.0f,false},
{"player_mp5",2,(ProjectileNature)1,-1.0f,-1.0f,false},
{"player_357",3,(ProjectileNature)1,-1.0f,-1.0f,false},
{"player_buckshot",4,(ProjectileNature)1,-1.0f,-1.0f,false},
{"player_crowbar",5,(ProjectileNature)2,-1.0f,-1.0f,false},
{"monster_9mm",6,(ProjectileNature)1,-1.0f,-1.0f,false},
{"monster_mp5",7,(ProjectileNature)1,-1.0f,-1.0f,false},
{"monster_12mm",8,(ProjectileNature)1,-1.0f,-1.0f,false},
};
enum {ProjectileCount=sizeof(projectiles)/sizeof(projectiles[0])};
static const char* const catalogSha256="603e55a569b43897df64b1339296814d212dafe6448b9f50d4c4f85609d52a70";
}
#endif
