// Generated by vector-fields/build_effects.py.
#ifndef VF_STATUS_CATALOG_H
#define VF_STATUS_CATALOG_H
namespace vfs {
enum Id {S_hydro,S_electro,S_cryo,S_thermal,S_toxic,S_corrosion,S_sonic,S_kinetic,S_arc_chain,S_superconduction,S_shatter,S_resonant_impact,S_cavitation,S_caustic_contagion,S_toxic_ignition,S_steam_veil,S_phase,S_null,S_ward,S_reveal,S_overclock};
struct Effect { const char *id; int kind,a,b; };
static const Effect effects[]={
{"hydro",0,-1,-1},
{"electro",0,-1,-1},
{"cryo",0,-1,-1},
{"thermal",0,-1,-1},
{"toxic",0,-1,-1},
{"corrosion",0,-1,-1},
{"sonic",0,-1,-1},
{"kinetic",0,-1,-1},
{"arc_chain",1,0,1},
{"superconduction",1,1,2},
{"shatter",1,2,7},
{"resonant_impact",1,7,6},
{"cavitation",1,6,5},
{"caustic_contagion",1,5,4},
{"toxic_ignition",1,4,3},
{"steam_veil",1,3,0},
{"phase",2,-1,-1},
{"null",2,-1,-1},
{"ward",2,-1,-1},
{"reveal",2,-1,-1},
{"overclock",2,-1,-1},
};
enum { Count=sizeof(effects)/sizeof(effects[0]) };
inline int Reaction(int a,int b){for(int i=0;i<Count;++i)if(effects[i].kind==1&&((effects[i].a==a&&effects[i].b==b)||(effects[i].a==b&&effects[i].b==a)))return i;return -1;}
}
#endif
