// Generated by build_weapon_fx.py. Do not edit.
#ifndef VF_WEAPON_FX_CATALOG_H
#define VF_WEAPON_FX_CATALOG_H
namespace vfshot {
struct Profile { const char* id; const char* name; int color[3]; float muzzleSize,muzzleLife,trailLife,trailWidth; int particles; float particleLife,lightRadius,decalSize; };
static const int Count=8; static const int Default=7;
static const Profile profiles[Count]={
{"hydro","Hydro",{70,175,255},10.0f,0.1f,0.13f,12.0f,7,0.65f,100.0f,6.0f},
{"electro","Electro",{255,205,80},12.0f,0.08f,0.1f,3.0f,8,0.35f,150.0f,4.0f},
{"cryo","Cryo",{125,230,255},11.0f,0.11f,0.13f,3.5f,7,0.7f,100.0f,5.0f},
{"thermal","Thermal",{255,112,45},13.0f,0.08f,0.09f,2.5f,7,0.55f,150.0f,5.0f},
{"toxic","Toxic",{176,95,230},9.0f,0.13f,0.17f,6.0f,8,0.9f,65.0f,5.0f},
{"corrosion","Corrosion",{205,235,60},10.0f,0.12f,0.15f,7.0f,7,0.75f,75.0f,6.0f},
{"sonic","Sonic",{255,145,215},12.0f,0.12f,0.16f,10.0f,5,0.4f,100.0f,7.0f},
{"kinetic","Kinetic",{210,200,175},12.0f,0.065f,0.085f,1.8f,8,0.5f,135.0f,4.0f},
};
}
#endif
