// Generated by vector-fields/build_status_decals.py.
#ifndef VF_STATUS_DECAL_CATALOG_H
#define VF_STATUS_DECAL_CATALOG_H
namespace vfdecal {
struct Asset {const char* id;float fps;};
static const Asset assets[]={
{"hydro",3.6f},
{"electro",5.6f},
{"cryo",2.4f},
{"thermal",4.8f},
{"toxic",2.6f},
{"corrosion",3.2f},
{"sonic",3.8f},
{"kinetic",2.8f},
{"arc_chain",4.6f},
{"superconduction",3.6f},
{"shatter",3.2f},
{"resonant_impact",3.8f},
{"cavitation",3.6f},
{"caustic_contagion",2.8f},
{"toxic_ignition",4.4f},
{"steam_veil",2.6f},
};
enum {Count=sizeof(assets)/sizeof(assets[0]),Frames=4};
static const float Border=0.14f;
static const float Opacity=0.72f;
}
#endif
