"""Convert original RGBA status flipbooks into native color and opacity sprites.
Offline and incremental: generated art is checked in, never generated at launch.
"""
import argparse, hashlib, json, math, struct
from pathlib import Path
from PIL import Image, ImageChops, ImageDraw
import build_cache
ROOT=Path(__file__).resolve().parent
ASSETS=ROOT/'assets/status-feedback/decals'
OUT=ROOT/'generated/status-decals'
CONFIG=ROOT/'data/status_decals.json'
HEADER=ROOT.parent/'cl_dll/vf_status_decal_catalog.h'

def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()

def native_sprite(path, frames):
    # The shipped Xash renderer supports native 32-bit sprites. RGBA retains
    # real opacity and both reaction colors, without additive whitening.
    size=frames[0].width
    # Version 32 uses the Quake layout (36 bytes, without texFormat).
    data=bytearray(struct.pack('<4siifiiifi',b'IDSP',32,2,size*math.sqrt(.5),size,size,len(frames),0.,0))
    for frame in frames:data+=struct.pack('<iiiii',0,-size//2,size//2,size,size)+frame.tobytes()
    path.write_bytes(data)

def registered_frames(sheet, size, border):
    width=sheet.width//2
    cells=[sheet.crop(((i%2)*width,(i//2)*width,(i%2+1)*width,(i//2+1)*width)) for i in range(4)]
    # Measure all four frames together: trim different generated margins, then
    # fit each material's actual depth to one common edge footprint. Never
    # recenter individual frames, which would make the animation jump.
    alphas=[list(c.getchannel('A').getdata()) for c in cells]
    begin=round(width*.20);end=round(width*.80);limit=round(width*.30)
    bounds=[]
    for edge in range(4):
        profile=[]
        for d in range(limit):
            total=0
            for alpha in alphas:
                if edge==0:total+=sum(alpha[y*width+d] for y in range(begin,end))
                if edge==1:total+=sum(alpha[y*width+width-1-d] for y in range(begin,end))
                if edge==2:total+=sum(alpha[d*width+x] for x in range(begin,end))
                if edge==3:total+=sum(alpha[(width-1-d)*width+x] for x in range(begin,end))
            profile.append(total)
        peak=max(profile);assert peak>0
        outer=next(i for i,value in enumerate(profile) if value>=peak*.20)
        total=sum(profile[outer:]);running=0;inner=outer+1
        for d in range(outer,len(profile)):
            running+=profile[d]
            if running>=total*.94:inner=d+1;break
        bounds.append((outer,max(outer+4,inner)))
    l,r,t,b=bounds
    dest=[0,round(size*border),round(size*(1-border)),size]
    source_x=[l[0],l[1],width-r[1],width-r[0]]
    source_y=[t[0],t[1],width-b[1],width-b[0]]
    mesh=[]
    for y in range(3):
        for x in range(3):
            box=(dest[x],dest[y],dest[x+1],dest[y+1])
            quad=(source_x[x],source_y[y],source_x[x],source_y[y+1],source_x[x+1],source_y[y+1],source_x[x+1],source_y[y])
            mesh.append((box,quad))
    result=[c.transform((size,size),Image.Transform.MESH,mesh,Image.Resampling.BICUBIC) for c in cells]
    return result,dict(source_size=width,edge_bounds=bounds,target_border=border)

def build(ensure=False):
    config=json.loads(CONFIG.read_text())
    effects=json.loads((ROOT/'data/effects.json').read_text())['effects']
    entries=config['effects']
    assert [e['id'] for e in entries]==[e['id'] for e in effects if e['kind'] in (0,1)]
    assert len(entries)==16 and config['frame_count']==4 and config['size']==512
    assert .1<=config['opacity']<=.9 and 0<config['fade_start']<config['border']<.16
    inputs=[Path(__file__),Path(build_cache.__file__),CONFIG,ROOT/'data/effects.json']+[ASSETS/'sources'/e['sheet'] for e in entries]
    fingerprint=build_cache.fingerprint(inputs)
    manifest=OUT/'manifest.json'
    if ensure and build_cache.current(build_cache.read(manifest).get('cache'),fingerprint):
        print('Current custom HUD decals: 16 flipbooks / 64 frames, verified outputs');return
    OUT.mkdir(parents=True,exist_ok=True);
    for obsolete in OUT.glob('*-mask.spr'):
        assert obsolete.resolve().parent==OUT.resolve();obsolete.unlink()
    (ASSETS/'frames').mkdir(exist_ok=True)
    size=config['size'];border=config['border'];start=config['fade_start']
    # Asset cleanup only: preserve generated colors/alpha while guaranteeing a
    # clear aim region even when a source wisp extends past the requested edge.
    protection=Image.frombytes('L',(size,size),bytes(round(255*max(0,min(1,(border-min(x+.5,y+.5,size-x-.5,size-y-.5)/size)/(border-start)))) for y in range(size) for x in range(size)))
    outputs=[];reports=[];gallery=Image.new('RGB',(4*384,4*252),(22,25,31));draw=ImageDraw.Draw(gallery)
    header=['// Generated by vector-fields/build_status_decals.py.','#ifndef VF_STATUS_DECAL_CATALOG_H','#define VF_STATUS_DECAL_CATALOG_H','namespace vfdecal {','struct Asset {const char* id;float fps;};','static const Asset assets[]={']
    for i,entry in enumerate(entries):
        source=ASSETS/'sources'/entry['sheet'];sheet=Image.open(source).convert('RGBA');w,h=sheet.size
        assert w==h and w%2==0 and sheet.getchannel('A').getextrema()[0]==0,source
        frames,registration=registered_frames(sheet,size,border)
        for frame,tile in enumerate(frames):
            tile.putalpha(ImageChops.multiply(tile.getchannel('A'),protection))
            target=ASSETS/'frames'/(entry['id']+'-'+str(frame)+'.png');tile.save(target);outputs.append(target)
        color=OUT/(entry['id']+'.spr')
        native_sprite(color,frames);outputs.append(color)
        assert 1<=entry['fps']<=6
        header.append('{"'+entry['id']+'",'+str(float(entry['fps']))+'f},')
        x=(i%4)*384;y=(i//4)*252
        for variant,bg in enumerate(((36,40,48),(208,209,203))):
            tile=frames[0].resize((184,184),Image.Resampling.LANCZOS);panel=Image.new('RGBA',tile.size,(*bg,255));panel.alpha_composite(tile)
            gallery.paste(panel.convert('RGB'),(x+4+variant*188,y+28))
        draw.text((x+8,y+8),effects[i]['hud_name'],fill=(235,235,235))
        draw.text((x+8,y+220),entry['id']+' / 4 frames',fill=(165,178,190))
        reports.append(dict(id=entry['id'],source_sha256=sha(source),frames=4,fps=entry['fps'],color=sha(color),registration=registration))
    header+=['};','enum {Count=sizeof(assets)/sizeof(assets[0]),Frames=4};','static const float Border='+str(border)+'f;','static const float Opacity='+str(config['opacity'])+'f;','}','#endif']
    HEADER.write_text('\n'.join(header)+'\n');outputs.append(HEADER)
    preview=ASSETS/'contact-sheet.png';gallery.save(preview);outputs.append(preview)
    report=dict(version=1,effects=reports,sprites=16,frames=64,size=size,border=border,opacity=config['opacity'],blend='native RGBA, shared opacity, registered edge footprint',cache=build_cache.record(fingerprint,outputs))
    manifest.write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
    print('PASS custom HUD decals: 16 distinct flipbooks, 64 original frames, 16 native RGBA sprites')
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--ensure',action='store_true');build(p.parse_args().ensure)
