"""Validate physical material definitions and generate the server/shared catalog."""
import hashlib,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parent
SOURCE=ROOT/'data/combat-materials.json'
TARGET=ROOT.parent/'game_shared/vf_material_catalog.h'

def build():
 c=json.loads(SOURCE.read_text(encoding='utf-8-sig'));assert c['schema']==1 and c['mode']=='identify_only'
 def key(s):assert re.fullmatch('[a-z][a-z0-9_]{0,39}',s),s;return s
 def number(v):
  if v is None:return '-1.0f'
  assert type(v) in (float,int)and 0<=v<1e8 and v==v;return f'{float(v):.6f}f'
 mids=[key(m['id'])for m in c['materials']];pids=[key(p['id'])for p in c['profiles']]
 assert len(set(mids))==len(mids)and mids[0]=='unknown'and len(set(pids))==len(pids)and pids[0]=='unknown'
 lines=['// Generated by vector-fields/build_materials.py; edit data/combat-materials.json.','#ifndef VF_MATERIAL_CATALOG_H','#define VF_MATERIAL_CATALOG_H','namespace vfc {','struct Material {const char* id;const char* family;float densityKgM3,resistanceJPerMm;bool calibrated;};','struct LayerDefinition {int material;float thicknessMm;};','struct Profile {const char* id;int count;LayerDefinition layers[4];};','enum MaterialId {'+','.join('Mat_'+x+'='+str(i)for i,x in enumerate(mids))+',MaterialCount};','enum ProfileId {'+','.join('Profile_'+x+'='+str(i)for i,x in enumerate(pids))+',ProfileCount};','static const Material materials[MaterialCount]={']
 for m in c['materials']:
  assert type(m['calibrated']) is bool
  assert not m['calibrated'] or (m['density_kg_m3'] is not None and m['density_kg_m3']>0 and m['ballistic_resistance_j_per_mm'] is not None),m['id']
  lines.append('{"'+m['id']+'","'+key(m['family'])+'",'+number(m['density_kg_m3'])+','+number(m['ballistic_resistance_j_per_mm'])+','+str(bool(m['calibrated'])).lower()+'},')
 lines+=['};','static const Profile profiles[ProfileCount]={']
 for p in c['profiles']:
  assert 0<len(p['layers'])<=4
  rows=['{Mat_'+l['material']+','+number(l['thickness_mm'])+'}'for l in p['layers']];assert all(l['material']in mids for l in p['layers'])
  lines.append('{"'+p['id']+'",'+str(len(rows))+',{'+','.join(rows+['{Mat_unknown,-1.0f}']*(4-len(rows)))+'}},')
 # Follow the real equipment key order, rather than duplicating numeric indices.
 shared=(ROOT.parent/'game_shared/vf_loadout.cpp').read_text(encoding='utf-8-sig')
 slots=re.findall(r'"([^"]+)"',re.search(r'SlotKeys\[SlotCount\]=\{([^}]+)',shared)[1])
 assert len(slots)==21 and set(c['slot_profiles'])==set(slots) and all(v in pids for v in c['slot_profiles'].values())
 lines+=['};','enum EquipmentSlot {'+','.join('Slot_'+k+'='+str(i)for i,k in enumerate(slots))+'};']
 lines+=['static const int slotProfiles[21]={'+','.join('Profile_'+c['slot_profiles'][k] for k in slots)+'};','struct ItemOverride {const char* key;int profile;};','static const ItemOverride itemOverrides[]={']
 for r in c['item_overrides']:
  assert r['profile']in pids and re.fullmatch('[a-z][a-z0-9_-]{0,79}',r['key']);lines.append('{"'+r['key']+'",Profile_'+r['profile']+'},')
 lines+=['{"",Profile_unknown}};','inline int TextureMaterial(char type){switch(type){']
 for letter,m in c['texture_types'].items():assert len(letter)==1 and letter.isupper()and m in mids;lines.append("case '"+letter+"':return Mat_"+m+';')
 lines+=['default:return Mat_unknown;}}']
 kinds=['unknown','kinetic','blunt','thermal','explosive','chemical','electrical']
 lines+=['enum ProjectileNature {NatureUnknown,Kinetic,Blunt,Thermal,Explosive,Chemical,Electrical};','inline const char* NatureKey(ProjectileNature n){static const char* keys[]={"unknown","kinetic","blunt","thermal","explosive","chemical","electrical"};return keys[n>=NatureUnknown&&n<=Electrical?n:NatureUnknown];}','struct ProjectileDefinition {const char* id;int nativeType;ProjectileNature nature;float massKg,speedMS;bool calibrated;};','static const ProjectileDefinition projectiles[]={']
 assert len(c['native_projectiles'])==9 and len({r['id']for r in c['native_projectiles']})==9
 for i,r in enumerate(c['native_projectiles']):
  assert r['native_type']==i and r['nature']in kinds;key(r['id'])
  assert type(r['calibrated']) is bool
  assert not r['calibrated'] or (r['mass_kg'] is not None and r['mass_kg']>0 and r['speed_m_s'] is not None and r['speed_m_s']>0),r['id']
  lines.append('{"'+r['id']+'",'+str(i)+',(ProjectileNature)'+str(kinds.index(r['nature']))+','+number(r['mass_kg'])+','+number(r['speed_m_s'])+','+str(bool(r['calibrated'])).lower()+'},')
 lines+=['};','enum {ProjectileCount=sizeof(projectiles)/sizeof(projectiles[0])};','static const char* const catalogSha256="'+hashlib.sha256(SOURCE.read_bytes()).hexdigest()+'";','}','#endif','']
 text='\n'.join(lines)
 if not TARGET.exists()or TARGET.read_text(encoding='utf-8')!=text:TARGET.write_text(text,encoding='utf-8')
 print('Materials:',len(mids),'profiles:',len(pids),'mode:',c['mode']);return c
if __name__=='__main__':build()
