"""Compile the single-source visual effect catalog and stage installed HL sprites."""
import json, hashlib, shutil, struct
from pathlib import Path
ROOT=Path(__file__).resolve().parent
PATTERNS=['Drops','Rings','Arcs','Sparks','Shards','Cloud','Rise','Orbit','Burst','Chain','Collapse','Scan']
SPRITES=['bubble.spr','hotglow.spr','steam1.spr','fire.spr','white.spr']
def generate():
 data=json.loads((ROOT/'data/effects.json').read_text());effects=data['effects'];ids={e['id']:i for i,e in enumerate(effects)}
 assert len(ids)==len(effects) and len(effects)<=64
 base=[e['id'] for e in effects if e['kind']==0];assert len(base)==8
 assert all(e['kind']==0 for e in effects[:8]) and all(e['kind']!=0 for e in effects[8:])
 partners={k:set() for k in base};pairs=set()
 for e in effects:
  assert e['kind'] in (0,1,2) and 1<=len(e['layers'])<=3
  for key in ('id','name','origin','recipe','meaning','visual'):assert e[key].isascii() and len(e[key])<250
  for layer in e['layers']:
   assert layer['pattern'] in PATTERNS and 0<=layer['texture']<len(SPRITES) and 1<=layer['count']<=64
   assert .2<=layer['size']<=10 and .1<=abs(layer['speed'])<=3
   assert len(layer['color'])==3 and all(0<=c<=255 for c in layer['color'])
  if e['kind']==1:
   a,b=e['parents'];assert a!=b and a in base and b in base
   pair=tuple(sorted((a,b)));assert pair not in pairs;pairs.add(pair);partners[a].add(b);partners[b].add(a)
 assert len(pairs)==8 and all(len(v)==2 for v in partners.values()),partners
 q=lambda s:json.dumps(s,ensure_ascii=True)
 lines=['// Generated by vector-fields/build_effects.py. Edit data/effects.json.','#ifndef VF_EFFECT_CATALOG_H','#define VF_EFFECT_CATALOG_H','namespace vfx {','enum Pattern {'+','.join(PATTERNS)+'};','struct Layer { Pattern pattern; int texture,count; float r,g,b,size,speed; };','struct Effect { const char *id,*name,*origin,*recipe,*meaning,*visual; int kind,parentA,parentB; int color[3]; int layerCount; Layer layers[3]; };','static const Effect effects[]={']
 for e in effects:
  parents=e.get('parents',[]);par=[ids[p] for p in parents] if parents else [-1,-1]
  layers=[]
  for l in e['layers']:
   vals=[l['pattern'],str(l['texture']),str(l['count'])]+[str(float(c)/255)+'f' for c in l['color']]+[str(float(l[k]))+'f' for k in ('size','speed')]
   layers.append('{'+','.join(vals)+'}')
  lines.append('{'+','.join(q(e[k]) for k in ('id','name','origin','recipe','meaning','visual'))+','+','.join(map(str,[e['kind']]+par))+',{'+','.join(map(str,e['color']))+'},'+str(len(layers))+',{'+','.join(layers)+'}},')
 lines+=['};','static const int Count=sizeof(effects)/sizeof(effects[0]);','inline int Reaction(int a,int b){ for(int i=0;i<Count;++i)if(effects[i].kind==1&&((effects[i].parentA==a&&effects[i].parentB==b)||(effects[i].parentA==b&&effects[i].parentB==a)))return i;return -1;}','}','#endif']
 (ROOT.parent/'cl_dll/vf_effect_catalog.h').write_text('\n'.join(lines)+'\n')
 out=ROOT/'generated/effects';out.mkdir(parents=True,exist_ok=True);audit=[]
 for name in SPRITES:
  src=Path('F:/SteamLibrary/steamapps/common/Half-Life/valve/sprites')/name
  raw=src.read_bytes();head=struct.unpack_from('<4siiifiiifi',raw);assert head[0]==b'IDSP' and head[1]==2
  shutil.copy2(src,out/name);audit.append(dict(file=name,source=str(src),sha256=hashlib.sha256(raw).hexdigest(),width=head[5],height=head[6],frames=head[7],bytes=len(raw)))
 report=dict(effects=len(effects),elements=base,reactions=len(pairs),partners={k:sorted(v) for k,v in partners.items()},sprites=audit,history='Partial conversation excerpt only; previous generated images unavailable. Six reactions explicitly proposed.')
 (ROOT/'build/effects-catalog-verification.json').write_text(json.dumps(report,indent=2))
 print('PASS catalog: 8 elements, 2 partners each, 8 reactions, 5 tactical cues;',len(audit),'HL sprites')
if __name__=='__main__':generate()
