"""Build a local high-resolution HUD font atlas for the native workshop."""
from pathlib import Path
import struct,math
from PIL import Image,ImageDraw,ImageFont
ROOT=Path(__file__).resolve().parent
out=ROOT/'generated/ui';out.mkdir(parents=True,exist_ok=True)
font=ImageFont.truetype('C:/Windows/Fonts/segoeui.ttf',32)
im=Image.new('L',(1024,512),0);draw=ImageDraw.Draw(im);widths=[]
for i in range(96):
 ch=chr(32+i);x=(i%16)*48;y=(i//16)*56
 draw.text((x+2,y),ch,font=font,fill=255)
 widths.append(round(float(font.getlength(ch))/2,3))
w,h=im.size
sprite=struct.pack('<4siiifiiifi',b'IDSP',2,2,0,math.hypot(w,h)/2,w,h,1,0.,0)
sprite+=struct.pack('<H',256)+b''.join(bytes([v,v,v]) for v in range(256))
sprite+=struct.pack('<iiiii',0,-w//2,h//2,w,h)+im.tobytes()
(out/'ui_font.spr').write_bytes(sprite)
(ROOT.parent/'cl_dll/vf_ui_font.h').write_text('// Generated by vector-fields/build_ui.py from the local Windows UI font.\nstatic const float vfFontAdvance[96]={'+','.join(str(x)+'f' for x in widths)+'};\n',encoding='ascii')
print('UI font atlas:',len(sprite),'bytes')
