"""Generate the shared effect-to-motion atlas from one reviewed data file."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
DATA=ROOT/'assets/animations/death-atlas.json'
def generate():
 d=json.loads(DATA.read_text());motions=d['motions'];ids=[m['id'] for m in motions];assert len(ids)==len(set(ids))
 rows=['// Generated by death_atlas.py from assets/animations/death-atlas.json.','#ifndef VF_DEATH_MOTION_H','#define VF_DEATH_MOTION_H','namespace vfmotion {','struct Motion { const char* id; const char* label; const char* sequence; };','static const Motion Motions[]={']
 for m in motions:rows.append(' {'+json.dumps(m['id'])+','+json.dumps(m['label'])+','+(json.dumps(m['sequence']) if m['sequence'] else '0')+'},')
 rows+=['};','static const int Count=sizeof(Motions)/sizeof(Motions[0]);','}','#endif'];(ROOT.parent/'game_shared/vf_death_motion.h').write_text('\n'.join(rows)+'\n')
 rows=['// Generated by death_atlas.py; order matches vf_status_catalog.h.','#ifndef VF_DEATH_ATLAS_H','#define VF_DEATH_ATLAS_H','#include "vf_death_motion.h"','namespace vfdeath {','struct Profile {const char* effect;const char* label;int motions[2],count;float fxSeconds;};','static const Profile Profiles[]={']
 for p in d['profiles']:
  pool=[ids.index(id) for id in p['motions']];assert 1<=len(pool)<=2 and all(i>=2 for i in pool);rows.append('{'+json.dumps(p['effect'])+','+json.dumps(p['label'])+',{'+','.join(str(i) for i in (pool+[0])[:2])+'},'+str(len(pool))+','+str(p['fx_seconds'])+'f},')
 rows+=['};','static const int ProfileCount=sizeof(Profiles)/sizeof(Profiles[0]);','inline const Profile* ProfileFor(int effect){return effect>=0&&effect<ProfileCount?&Profiles[effect]:0;}','inline int AutomaticMotion(int effect,int missing,int choice){const Profile* p=ProfileFor(effect);if(p)return p->motions[(unsigned int)choice%p->count];if(missing&1)return '+str(ids.index('headshot'))+';return 2+(unsigned int)choice%3;}','}','#endif'];(ROOT.parent/'game_shared/vf_death_atlas.h').write_text('\n'.join(rows)+'\n');return d
def inventory():
 """Measured shortlist and complete file-name index of the acquired catalogue."""
 import hashlib
 import numpy as np
 from external_death_animations import Gltf,ASSETS
 d=json.loads(DATA.read_text());selected={m.get('source_file'):m for m in d['motions'] if 'source_file' in m}
 notes={
 'Crouch_Death':('reserve','Depart accroupi : a conditionner a la posture du joueur.'),
 'Death_Crouching_Headshot_Front':('excluded','Ce fichier se termine debout dans le miroir inspecte ; le nom ne suffit pas.'),
 'Falling_Down':('reserve','Chute exploitable, reserve aux pertes d equilibre.'),
 'Falling_Flat_Impact':('reserve','Commence deja en l air ; convient a une chute depuis une hauteur.'),
 'Flying_Back_Death':('excluded','Le fichier inspecte se releve et se termine debout.'),
 'Hit_Reaction':('excluded','Reaction a un coup suivie de recuperation, pas une mort complete.'),
 'Injured_Hurting_Idle':('excluded','Boucle de blessure sans chute finale ; derive horizontale.'),
 'Injured_Stumble_Idle':('excluded','Titubement puis recuperation, utilisable comme amorce future.'),
 'Livershot_Knockdown':('excluded','La cible se releve ; 9.17 s, ne pas figer en cadavre.'),
 'Mutant_Dying':('reserve','Chute complete mais gestuelle de creature a reserver aux ennemis appropries.'),
 'Rifle_Run_To_Dying':('reserve','Mort en course avec 4 m de translation source ; contexte locomotion requis.'),
 'Standing_Death_Backward_01':('excluded','Le fichier du miroir se termine debout ; ecarte apres mesure.'),
 'Sword_And_Shield_Death':('reserve','Chute complete, pose des mains associee a une arme et un bouclier.'),
 'Two_Handed_Sword_Death':('reserve','Chute complete, pose des mains associee a une arme a deux mains.'),
 'Walking_To_Dying':('excluded','Pas de chute finale dans ce fichier inspecte.'),
 'Zombie_Death':('reserve','Chute complete avec posture de zombie.'),
 'Zombie_Dying':('reserve','Chute complete avec posture de zombie.')}
 records=[]
 for path in sorted(ASSETS.glob('mixamo-*.glb')):
  source=Gltf(path);clip=source.doc['animations'][0]['name'];frames,seconds=source.sample(clip);hips=source.names['mixamorig:Hips'];head=source.names['mixamorig:Head'];name=path.stem.removeprefix('mixamo-')
  decision,reason=('integrated',selected[path.name]['label']) if path.name in selected else notes[name]
  records.append(dict(file=path.name,source_name=name,duration_seconds=round(seconds,6),sampled_poses=len(frames),decision=decision,reason=reason,sequence=selected[path.name]['sequence'] if path.name in selected else None,hips_height_start_end=frames[[0,-1],hips,1,3].tolist(),head_height_start_end=frames[[0,-1],head,1,3].tolist(),source_units='metres, Y up',sha256=hashlib.sha256(path.read_bytes()).hexdigest()))
 tree=json.loads((ASSETS/'mixamo-inventory.json').read_text());all_files=[n['path'] for n in tree['tree'] if n['path'].startswith('anim/') and n['path'].endswith('.glb')];assert len(all_files)==886
 other=[]
 for file in ['quaternius-standard.gltf','kaykit-general.glb']:
  source=Gltf(ASSETS/file);other.append(dict(file=file,animations=[a['name'] for a in source.doc['animations']],death_clips=['Death01'] if file.startswith('quaternius') else ['Death_A','Death_B']))
 result=dict(schema=1,reviewed='2026-10-10',scope='Catalogue public deevid-mixamo-assets et banques Quaternius/KayKit acquises ; ne pretend pas couvrir toutes les banques Internet.',source='https://github.com/MisterYI/deevid-mixamo-assets',author='https://www.mixamo.com/',git_tree=tree['sha'],catalogue_animations=len(all_files),inspected_candidates=records,catalogue_files=all_files,other_banks=other)
 (ASSETS.parent/'death-inventory.json').write_text(json.dumps(result,indent=2)+'\n')
 rows=['# Atlas des morts et fragments elementaires','', 'Le jeu contient dix animations de mort importees : trois Quaternius/KayKit et sept Mixamo, plus les sept morts historiques et la contraction electrique personnalisee. L atlas couvre les huit elements et les huit reactions. Une meme gestuelle peut servir a plusieurs reactions ; leurs particules donnent la signature de la combinaison.','', '## Choix et essai en jeu','', 'Lancer `Jouer - Vector Fields.cmd`, puis **F4** pour la salle et **F8** pour les morts. L onglet **Atlas** propose les elements puis les reactions. Choisir un effet et une zone a droite provoque une mort avec le mouvement automatique correspondant. **Catalogue** contient trois pages de mouvements a imposer manuellement.','', '| Effet | Gestuelle automatique | Particules des morceaux |','|---|---|---|']
 signatures=['Gouttes bleues et rides','Arcs et etincelles ambre','Eclats cyan et brume froide','Flammes et braises orange','Spores violettes','Gouttes et bulles acides vert jaune','Ondes roses','Traits d impact et etincelles','Gouttes bleues et arcs ambre','Cristaux bleus et arcs blancs','Eclats et gerbe blanche','Ondes roses et eclats couleur metal','Bulles acides, ondes et gouttes','Brume verte, gouttes et spores violettes','Brume et flammes','Vapeur blanche et gouttes bleues']
 for i,profile in enumerate(d['profiles']):rows.append('| '+profile['effect']+' | '+profile['label']+' ('+', '.join(profile['motions'])+') | '+signatures[i]+' |')
 rows+=['','## Inventaire verifie','', '[Mixamo](https://www.mixamo.com/) fournit les mouvements ; le [miroir GLB inspecte](https://github.com/MisterYI/deevid-mixamo-assets) contient 886 animations. Les 24 candidats ci-dessous ont ete telecharges et leurs courbes mesurees, puis sept ont ete adaptes au GIGN. Les noms ne garantissent pas le contenu : plusieurs fichiers inspectes se terminent debout et sont ecartes. La liste integrale des 886 fichiers et les empreintes sont dans `assets/animations/death-inventory.json`.','', '[Quaternius](https://quaternius.itch.io/universal-animation-library) et [KayKit](https://kaylousberg.itch.io/kaykit-character-animations) complètent cet inventaire avec les trois morts deja transferees. Leurs catalogues locaux sont egalement recenses dans le JSON.','', '| Candidat Mixamo | Duree | Decision | Motif |','|---|---:|---|---|']
 for c in records:rows.append('| '+c['source_name']+' | '+str(round(c['duration_seconds'],2))+' s | '+c['decision']+' | '+c['reason']+' |')
 rows+=['','## Membres et presentation','', 'Chaque zone retiree genere une piece anatomique reconnaissable et trois petits fragments, habilles selon le theme de la victime. Ce sont des entites Studio propulsees, soumises a la gravite et aux collisions du decor. Elles ne se bloquent pas entre elles ni contre les personnages. Au repos, la piece entiere est orientee et posee au sol selon les dimensions mesurees de son maillage. Les coupes utilisent les textures de plaies existantes.','', 'Pendant les 2,2 premieres secondes de mouvement, les morceaux emettent du sang et les couches visuelles de leur effet. Les particules conservent leur position dans le monde, leur vitesse et leur duree : la trainee reste derriere le membre. Une reaction conserve toutes ses couches (deux ou trois). Le cadavre porte sa propre signature pendant la duree indiquee dans l atlas, jusqu a 6,2 secondes pour l agonie.','', 'Le serveur diffuse l effet, l age, le modele de fragment et un identifiant de generation. Les nouveaux observateurs recuperent l age reel ; ils ne rejouent pas une explosion ancienne. Les morceaux expirent a 12 secondes et le cadavre a 15 secondes. Limites : 12 cadavres, 72 entites de fragments, 384 particules elementaires simultanees et 12 emissions par image.','', 'Les mouvements sont transferes sur les 28 os GIGN ; les longueurs des membres sont conservees. Les poses sont ajustees au maillage decoupe reel pour eviter les contacts sous le sol et garder le torse au sol en fin de chute. Les 77 sequences historiques et les indices des trois imports precedents sont conserves. Les quatre attaches du modele restent inchangees.','', 'Ces gestuelles representent les effets par interpretation artistique ; les banques ne proposent pas toutes une mort acide ou electrique nommee comme telle. Les seuils de degats par zone restent a definir, comme convenu. Les commandes de test restent `vf_range_death <0..3> <zone> <effet> [mouvement]` et `vf_death_test <zone> <effet> [mouvement]`.','', '## Validation','', 'Les rapports et captures natifs sont dans `docs/validation/death-atlas/`. Les suites verifient les 16 associations automatiques, les cinq zones anatomiques, les trajectoires et particules, le choix par F8, la sauvegarde du cadavre, les budgets et la synchronisation reseau.']
 (ROOT/'docs/DEATH-ATLAS.md').write_text('\n'.join(rows)+'\n',encoding='utf-8')
 print('Inventory:',len(all_files),'catalogue clips,',len(records),'inspected,',len(selected),'new imports')
 return result
if __name__=='__main__':generate();inventory()
