"""One model contract for Python authors, the client and the server."""
import argparse
import json
import re
from pathlib import Path
ROOT = Path(__file__).resolve().parent
PATH = ROOT/'data/model_contract.json'
HEADER = ROOT.parent/'game_shared/vf_model_contract.h'


def load(path=PATH):
    data = json.loads(Path(path).read_text(encoding='utf-8-sig'))
    if data.get('schema') != 1:
        raise ValueError('Unsupported model contract schema')
    platforms = data['platforms']
    if [p['id'] for p in platforms] != ['bottom', 'side', 'top']:
        raise ValueError('Feed mount order must remain bottom, side, top')
    for p in platforms:
        for key in ('first_person', 'foregrip', 'third_person'):
            if not re.fullmatch(r'models/vf_r01/[a-z0-9_]+\.mdl', p[key]) or len(p[key]) >= 64:
                raise ValueError(f'Unsafe carrier path: {p[key]}')
    for key, spec in data['receivers'].items():
        if not re.fullmatch(r'r01_receiver_[a-z0-9_]+', key) or spec['feed_mount'] not in ('bottom', 'side', 'top'):
            raise ValueError(f'Invalid receiver trait: {key}')
    for key, spec in data['underbarrels'].items():
        if not re.fullmatch(r'r01_underbarrel_[a-z0-9_]+', key) or type(spec['support_grip']) is not bool:
            raise ValueError(f'Invalid support grip trait: {key}')
    for view in ('first_person', 'third_person'):
        sockets = data['sockets'][view]
        if set(sockets) != {'weapon', 'feed', 'chamber'} or len(set(sockets.values())) != 3:
            raise ValueError(f'Invalid {view} sockets')
        for name in sockets.values():
            if not re.fullmatch(r'[A-Za-z0-9_ ]{1,31}', name):
                raise ValueError(f'Invalid socket name: {name}')
        bones = data['skeletons'][view]
        if not bones or len(set(bones)) != len(bones):
            raise ValueError(f'Invalid {view} skeleton')
    if type(data['persona_sequences']) is not int or data['persona_sequences'] <= 0:
        raise ValueError('Invalid persona sequence count')
    return data


def check_skeleton(names, view, data=None):
    expected = (data or load())['skeletons'][view]
    actual = list(names.values()) if isinstance(names, dict) else list(names)
    if actual[:len(expected)] != expected:
        raise ValueError(f'{view} skeleton differs from model_contract.json; review the authored joint mapping')


def header(data):
    platforms = data['platforms']
    lines = ['// Generated by model_contract.py from data/model_contract.json; do not edit.',
             '#ifndef VF_MODEL_CONTRACT_H', '#define VF_MODEL_CONTRACT_H', '#include <string.h>', 'namespace vf {',
             'struct ModelTraits { const char* key; int feedMount; bool supportGrip; };',
             'static const ModelTraits ModelTraitTable[] = {']
    for key, spec in data['receivers'].items():
        mount = [p['id'] for p in platforms].index(spec['feed_mount'])
        lines.append(' {"%s", %d, false},' % (key, mount))
    for key, spec in data['underbarrels'].items():
        lines.append(' {"%s", 0, %s},' % (key, str(spec['support_grip']).lower()))
    lines += ['};', 'inline const ModelTraits* FindModelTraits(const char* key) {',
              ' if(!key)return NULL;',
              ' for(unsigned int i=0;i<sizeof(ModelTraitTable)/sizeof(*ModelTraitTable);++i)',
              '  if(!strcmp(key,ModelTraitTable[i].key))return &ModelTraitTable[i];', ' return NULL;', '}',
              'struct ModelCarrier { const char* firstPerson; const char* foregrip; const char* thirdPerson; };',
              'static const ModelCarrier ModelCarriers[] = {']
    for p in platforms:
        lines.append(' {"%s", "%s", "%s"},' % (p['first_person'], p['foregrip'], p['third_person']))
    lines += ['};', 'inline const ModelCarrier& Carrier(int mount) { return ModelCarriers[mount>=0&&mount<3?mount:0]; }']
    for view, prefix in [('first_person', 'FirstPerson'), ('third_person', 'ThirdPerson')]:
        for role, name in data['sockets'][view].items():
            lines.append('static const char* const %s%sSocket = "%s";' % (prefix, role.title(), name))
    lines += ['static const int PersonaSequenceCount = %d;' % data['persona_sequences'], '}', '#endif', '']
    return '\n'.join(lines)


def generate(check=False):
    text = header(load())
    if check:
        if not HEADER.exists() or HEADER.read_text(encoding='ascii') != text:
            raise ValueError('Model contract header is stale; run python vector-fields/model_contract.py')
    elif not HEADER.exists() or HEADER.read_text(encoding='ascii') != text:
        HEADER.write_text(text, encoding='ascii')


if __name__ == '__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');generate(p.parse_args().check)
